### ISSUE TITLE
Addition of SSL

### ISSUE THREAD

**Issue by marwahmanbir** [hirosystems/btc-us-website#6]
As discussed on Discord - could the dev team add an SSL cert so that *.btc.us websites (using CNAME) are HTTPS compatible? It would be a really nice addition as that 'Not Secure' tag alongside the URL doesn't look cool. 😅

Would love to hear your thoughts on this. Thanks!

**Comment by 314159265359879** [comment]
copy of a piece of discussion on this from Discord
![image](https://user-images.githubusercontent.com/33360391/122466957-39788b00-cfba-11eb-8259-46332216afdf.png)

And some other thoughts
Do you also consider https://*.btc.us to redirect instead of the now default http://*.btc.us?
I think that would require an extra write to the zonefile (to include https)? and if using a wildcard SAN certificate is out of the question is there a way to let users use a service like Let's Encrypt to actually sign their own subdomain?

**Comment by wileyj** [comment]
Possible sure, but we're currently looking for a permanent home for this today. 
Once that's locked down, we can (indeed should) provide a wildcard SAN for btc.us

**Comment by wileyj** [comment]
i would say this can't be done in a reliable manner. you may have seen a previous reply from me, but i misunderstood the ask here. 

is this feasible? yes it is. but it's not a trivial undertaking since it would require whomever operates btc.us to also issue and maintain ssl certs for any CNAME target. 
alternatively, the SAN idea is normally how this would be done....but in this case we're allowing *any* SAN on the internet....so this cert would need a san that effectively uses `*.*`. again, not feasible. 

I would say this: only use a CNAME if you're going to point it to a service that provides a cert for that domain (i.e. github, or twitter etc). if you're wanting to point to a service you're planning on runninng on a VM or something -> use an A record.

**Comment by marwahmanbir** [comment]
If a *.btc.us website is based on GitHub pages (in my case), it uses both CNAME and A records.  
![Screenshot from 2021-06-18 12-00-41](https://user-images.githubusercontent.com/22788214/122517275-6fa32280-d02d-11eb-8905-5efaff0ff37c.jpg)
GitHub doesn't allow HTTPS until the website itself is using it natively.
![Screenshot from 2021-06-18 12-00-13](https://user-images.githubusercontent.com/22788214/122517362-88abd380-d02d-11eb-901c-20c1a72d0d1b.jpg)

Is there any other way I can move to HTTPS? Again, I know it's not feasible, but it would be a huge plus for all users if all the *.btc.us pages could support HTTPS.

**Comment by CharlieC3** [comment]
I agree with @wileyj, and I as well misunderstood the premise. The web bridge is **not** a sort of reverse proxy where its owner would be able to issue a wildcard SSL cert for all subdomains, install it on their end, and be done with it. It's in fact a DNS server for subdomains of the `btc.us` domain. Any hypothetical certificate created would have to be installed on the destination's side. So if you created a CNAME at `myname.btc.us` to point to `myname.github.io`, you'd have to contact _Github_ and somehow convince them to install an SSL cert you provide them to encrypt traffic coming in from `myname.btc.us`, which would not be possible. Let alone getting the owner of `btc.us` to hand over a certificate and their SSL private key.

@marwahmanbir For now you should be able to use the _redirect_ feature under the Accounts page.
![Screen Shot 2021-06-18 at 9 55 53 AM](https://user-images.githubusercontent.com/2747302/122572163-788af880-d01b-11eb-8490-ba223d5314e7.png)

Using this should make it act more like a `302` HTTP redirect where the URL changes, so HTTPS should work using this method. For example, http://marvin.btc.us redirects to Twitter over HTTPS.

**Comment by marwahmanbir** [comment]
@CharlieC3 thanks for the info! By adding a redirect, did you mean one pointing to username.github.io, or any other site? The thing is, I don't want the user to redirect to any other page such as my Twitter.

The GitHub pages are by default SSL enabled afaik, but I'm not sure if and how we can have that as a shared certificate on external domains such as *.btc.us - if you mean to say that.

**Comment by wileyj** [comment]
> GitHub doesn't allow HTTPS until the website itself is using it natively.

I'm not familiar with how github does this, but I am curious how they know you're using a `btc.us` domain name here. Is that something you've provided (or are required to provide to them?) - and secondly, is it possible to *not* tell github you're using a CNAME from `btc.us`?

**Comment by CharlieC3** [comment]
@wileyj You can tell Github to expect a custom domain when creating a Pages site like so:
![Screen Shot 2021-06-18 at 11 12 36 AM](https://user-images.githubusercontent.com/2747302/122582433-2ac7bd80-d026-11eb-9d6e-73767dc50b0b.png)

**Comment by marwahmanbir** [comment]
So I somehow managed to enable the 'Enforce HTTPS' option (which was not working earlier), but now my *.btc.us page isn't loading the background image. Is the jpeg file being considered as an insecure element? What should I do?

**Comment by marwahmanbir** [comment]
Update: I had to add a meta tag for Content-Security-Policy in the HTML. The background image issue is resolved and the site is now on HTTPS. :)
Thanks!

**Comment by CharlieC3** [comment]
@marwahmanbir Wow, glad it worked out! It seems Github reached out to Let's Encrypt to acquire a cert and is able to get the site verified automatically. I definitely learned something from this.

> It can take up to an hour for your site to become available over HTTPS after you configure your custom domain.

https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/troubleshooting-custom-domains-and-github-pages#https-errors

Closing this issue.

**Comment by MarvinJanssen** [comment]
Damn, that is cool.

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/5727806/122616518-5d31e480-d03f-11eb-97bf-cb8e1062a254.png">

**Comment by marwahmanbir** [comment]
Thanks @MarvinJanssen! :)
Do these certificates auto-renew post the expiration date? Or do I need to do anything?  

Also, kudos to the Stacks and Hiro team for the amazing work building this product!

**Comment by MarvinJanssen** [comment]
I'm sure GitHub will renew it automatically for you.

We're really starting to scratch the surface of what will be possible with BNS. Great job on leading the way here @marwahmanbir, definitely inspired me to try something like it soon.

**Comment by MarvinJanssen** [comment]
@marwahmanbir would you be open to creating a tutorial on how you got this done, by the way? I think many people would be interested.

**Comment by marwahmanbir** [comment]
@MarvinJanssen awesome!
Sure, I think I can do a tutorial in the form of blog. I have a few more things in mind - let me connect over Discord if that works better for you!
